### ISSUE TITLE
Freeze during starting process

### ISSUE THREAD

**Issue by Zkaface** [TheTemportalist/Compression#10] opened 2016-04-24 10:09 UTC
I'm not sure, but there seems to be an issue in this mod. During the starting process the server /client freezes and nothing is happening any more. No specific Error message appears. My mod list out of log:

http://pastebin.com/bLh0jUaH

**Comment by TheTemportalist** [comment] 2016-04-24 14:01
In my Experience with mod packs for 1.9, this is caused by blood magic. Please talk to WayOfTime.

**Comment by Zkaface** [comment] 2016-04-24 14:05
And so, the civil war started ;-) they've sent me to you :-P

**Comment by Phonavis** [comment] 2016-04-24 14:29
Yup, Way said to go to you ye...
He said it wasn't freezing though, it was just taking a metric shit ton of time because of Compression going through so many blocks or something...
I suppose a good temp fix would be if you added a config file to exclude mods going by the new ID system.
Though I thought the mod only applied to vanilla in the first place...

Oh, here's the issue on it for blood magic, to save you some time 
https://github.com/WayofTime/BloodMagic/issues/718

So now the question is if I should remove Compression or Blood magic until there is a fix...

**Comment by Zkaface** [comment] 2016-04-24 14:34
Yup, I gonna choose... the cap side... Or Tony... Idk. Of course I want for blood magic update, they produce a bunch of issues. Have a great one!

**Comment by Zkaface** [comment] 2016-04-24 14:41
*wait

**Comment by TehNut** [comment] 2016-04-24 15:46
You can close this. I added a bandaid here. https://github.com/WayofTime/BloodMagic/commit/ba17fe126e89f6d39e9dee5db69f48e7222580c0

But really, 3200 recipes for just Vanilla + BM is bad.

**Comment by TheTemportalist** [comment] 2016-04-24 16:28
I'll work on threading this after I get some work done.

**Closed as completed** 2016-04-24 18:38 UTC
Labels: bug
